import "./globals.css";
import type { Metadata } from "next";
import { roboto } from "../lib/utils/styles";
import { AuthProvider } from "../components/wrappers/AuthProvider";
import Header from "../components/Layout/Header";
import Font from "./Font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} dark`}>
        <AuthProvider>
          <div className="root-container">
            <div className="root-wrapper relative ">
              <div className="sticky top-0">
                <Header />
              </div>
              {children}
            </div>
          </div>
          <Font />
        </AuthProvider>
      </body>
    </html>
  );
}
